name: ' Update COSMO Alpaca System Files'

on:
  workflow_call:
    inputs:
      branch:
        description: Branch to update
        required: true
        type: string
      templateUrl:
        description: Template Repository URL
        required: false
        default: ''
        type: string
      downloadLatest:
        description: Download latest from template repository
        type: boolean
        default: true
      directCommit:
        description: Direct Commit?
        type: boolean
        default: false
      useInputCommitOptions:
        description: Use commit options from inputs
        type: boolean
        default: false

permissions:
  actions: read
  contents: read
  id-token: write

defaults:
  run:
    shell: pwsh

env:
  ALGoOrgSettings: ${{ vars.ALGoOrgSettings }}
  ALGoRepoSettings: ${{ vars.ALGoRepoSettings }}

jobs:
  ReadCommitOptions:
    name: Read Commit Options
    uses: ./.github/workflows/_AlpacaReadCommitOptions.yaml
    secrets: inherit
    with:
      branch: ${{ inputs.branch }}
      downloadLatest: ${{ inputs.downloadLatest }}
      directCommit: ${{ inputs.directCommit }}
      useInputCommitOptions: ${{ inputs.useInputCommitOptions }}

  UpdateAlpacaSystemFiles:
    name: "Update COSMO Alpaca System Files for branch '${{ inputs.branch }}'"
    needs: [ ReadCommitOptions ]
    runs-on: windows-latest  
    steps:  
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ inputs.branch }}
  
      - name: Read secrets
        id: ReadSecrets
        uses: microsoft/AL-Go-Actions/ReadSecrets@v7.2
        with:
          shell: pwsh
          gitHubSecrets: ${{ toJson(secrets) }}
          getSecrets: 'ghTokenWorkflow'
  
      - name: Update COSMO Alpaca system files
        uses: cosmoconsult/Alpaca-Actions/UpdateAlpacaSystemFiles@main
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          shell: pwsh
          token: ${{ fromJson(steps.ReadSecrets.outputs.Secrets).ghTokenWorkflow }}
          downloadLatest: ${{ needs.ReadCommitOptions.outputs.downloadLatest }}
          templateUrl: ${{ inputs.templateUrl }}
          directCommit: ${{ needs.ReadCommitOptions.outputs.directCommit }}
          updateBranch: ${{ inputs.branch }}
