name: '_COSMO Alpaca - Initialization'

on:
  workflow_call:
    inputs:
      checkoutRef:
        description: Ref to checkout
        required: false
        default: ${{ github.sha }}
        type: string
    outputs:
      checkoutRef:
        description: Ref to checkout
        value: ${{ inputs.checkoutRef }}
      backendUrl:
        value: ${{ jobs.Initialization.outputs.backendUrl }}
    

defaults:
  run:
    shell: powershell

permissions:
  actions: read
  contents: read
  id-token: write

env:
  ALGoOrgSettings: ${{ vars.ALGoOrgSettings }}
  ALGoRepoSettings: ${{ vars.ALGoRepoSettings }}
  ALPACA_BACKEND_URL: ${{ vars.ALPACA_BACKEND_URL }}

jobs:
  Initialization:
    name: COSMO Alpaca Initialization
    runs-on: [ ubuntu-latest ]
    outputs:
      templateUrl: ${{ steps.DetermineTemplateUrl.outputs.url }}
      backendUrl: ${{ steps.Initialization.outputs.backendUrl }}
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ inputs.checkoutRef }}
          lfs: true

      - id: Initialization
        name: Initialize COSMO Alpaca
        shell: powershell
        run: |
          ./.alpaca/PowerShell/Initialize-Alpaca.ps1

  