name: '[DEPRECATED]_COSMO Alpaca - Sync Configs'

on:
  workflow_call:

jobs:
  Deprecated:
    name: This workflow is deprecated
    runs-on: ubuntu-latest
    steps:
      - run: echo "::error::This reusable workflow has been moved and only exists for automatic removal in target repositories on update AL-Go system files. You can find the the moved files in the [Alpaca Actions](https://github.com/cosmoconsult/Alpaca-Actions) repository."
