name: '_COSMO Alpaca - Initialization'

on:
  workflow_call:
    inputs:
      checkoutRef:
        description: Ref to checkout
        required: false
        default: ${{ github.sha }}
        type: string
    outputs:
      checkoutRef:
        description: Ref to checkout
        value: ${{ inputs.checkoutRef }}
      backendUrl:
        value: ${{ jobs.Initialization.outputs.backendUrl }}
      scriptsArchiveUrl:
        value: ${{ jobs.Initialization.outputs.scriptsArchiveUrl }}
      scriptsArchiveDirectory:
        value: ${{ jobs.Initialization.outputs.scriptsArchiveDirectory }}
    

defaults:
  run:
    shell: powershell

permissions:
  actions: read
  contents: read
  id-token: write

jobs:
  Initialization:
    name: COSMO Alpaca Initialization
    runs-on: [ ubuntu-latest ]
    outputs:
      backendUrl: ${{ steps.Initialization.outputs.backendUrl }}
      scriptsArchiveUrl: ${{ steps.Initialization.outputs.scriptsArchiveUrl }}
      scriptsArchiveDirectory: ${{ steps.Initialization.outputs.scriptsArchiveDirectory }}
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ inputs.checkoutRef }}
          lfs: true

      - id: Initialization
        name: Initialization
        uses: cosmoconsult/Alpaca-Actions/Actions/Initialization@owun-refactor
        env:
          ALPACA_BACKEND_URL: ${{ vars.ALPACA_BACKEND_URL }}
        with:
          shell: powershell


  