name: 'Dispatch Update AL-Go System Files'

run-name: "Dispatch Update AL-Go System Files for [${{ github.ref_name }}]"

on:
  workflow_call:

permissions:
  actions: write
  contents: read

defaults:
  run:
    shell: pwsh

jobs:
  DispatchUpdateALGoSystemFiles:
    runs-on: [ ubuntu-latest ]
    steps:          
      - name: Dispatch Update AL-Go System Files workflow
        uses: actions/github-script@v7
        with:
          github-token: ${{ github.token }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'UpdateGitHubGoSystemFiles.yaml',
              ref: '${{ github.ref_name }}',
              inputs: {
                downloadLatest: 'false',
                directCommit: 'true'
              }
            });
