name: '_COSMO Alpaca - Remove Containers'

on:
  workflow_call:
    inputs:
      checkoutRef:
        description: Ref to checkout
        required: false
        default: ${{ github.sha }}
        type: string
      backendUrl:
        description: COSMO Alpaca Backend URL
        required: true
        type: string
      containersJson:
        description: JSON with COSMO Alpaca containers
        required: true
        type: string

defaults:
  run:
    shell: powershell

permissions:
  actions: read
  contents: read
  id-token: write

env:
  ALGoOrgSettings: ${{ vars.ALGoOrgSettings }}
  ALGoRepoSettings: ${{ vars.ALGoRepoSettings }}
  ALPACA_BACKEND_URL: ${{ inputs.backendUrl }}
  ALPACA_CONTAINERS_JSON: ${{ inputs.containersJson }}

jobs:
  RemoveAlpacaContainers:
    name: Remove COSMO Alpaca Containers
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ inputs.checkoutRef }}
          lfs: true

      - name: Remove COSMO Alpaca Containers
        shell: powershell
        run: |
          ./.alpaca/PowerShell/Remove-AlpacaContainers.ps1 -token "${{ secrets.GITHUB_TOKEN }}"