name: ' COSMO Alpaca - Test'

on:
  workflow_dispatch:

defaults:
  run:
    shell: powershell

permissions:
  actions: read
  contents: read
  id-token: write

env:
  ALGoOrgSettings: ${{ vars.ALGoOrgSettings }}
  ALGoRepoSettings: ${{ vars.ALGoRepoSettings }}

jobs:
  Upload:
    name: Upload
    runs-on: [ ubuntu-latest ]
    steps:  
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Upload COSMO Alpaca AL-Go Override Scripts
        uses: actions/upload-artifact@v4
        with:
          name: alpaca-algo-override-scripts
          path: ./.AL-GO/**/*.ps1

  Download:
    name: Download
    needs: [ Upload ]
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Download COSMO Alpaca AL-Go Override Scripts
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_RUN_ID: ${{ github.run_id }}
        run: |
          $headers = @{ Authorization = "Bearer ${{ secrets.GITHUB_TOKEN }}" }

          # Get list of artifacts
          $artifactsUrl = "https://api.github.com/repos/{0}/actions/runs/{1}/artifacts" -f $env:GITHUB_REPOSITORY, $env:GITHUB_RUN_ID
          $artifacts = Invoke-RestMethod -Uri $artifactsUrl -Headers $headers

          # Find the artifact by name
          $artifact = $artifacts.artifacts | Where-Object { $_.name -eq "alpaca-algo-override-scripts" }

          # Download the artifact
          $artifactUrl = $artifact.archive_download_url
          Invoke-RestMethod -Uri $artifactUrl -Headers $headers -OutFile "artifact.zip"

          # Unzip and run
          Expand-Archive -Path "artifact.zip" -DestinationPath ".alpaca/AL-Go"

          Get-ChildItem -Path "./.alpaca/AL-Go/*.ps1" | ForEach-Object {
            Write-Host "Override script: $($_.FullName)"
          }


  
  