name: ' Ensure COSMO Alpaca Template'

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/AL-Go-Settings.json'

defaults:
  run:
    shell: powershell

permissions:
  actions: read
  contents: read
  id-token: write

env:
  ALGoOrgSettings: ${{ vars.ALGoOrgSettings }}
  ALGoRepoSettings: ${{ vars.ALGoRepoSettings }}
  ALPACA_TEMPLATE_URL: ${{ vars.ALPACA_TEMPLATE_URL || 'https://github.com/cosmoconsult/Alpaca-PTE@main' }}

jobs:
  Initialization:
    name: Initialization
    runs-on: [ ubuntu-latest ]
    outputs:
      currentTemplateUrl: ${{ steps.DetermineTemplateUrls.outputs.currentTemplateUrl }}
      alpacaTemplateUrl: ${{ steps.DetermineTemplateUrls.outputs.alpacaTemplateUrl }}
    steps:  
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Read settings
        uses: microsoft/AL-Go/Actions/ReadSettings@ab2f5319ed073c542e03914f8ae6c0fda029ee1e
        with:
          shell: powershell
          get: templateUrl

      - name: Determine Template URLs
        id: DetermineTemplateUrls
        run: |
          Write-Host "Current Template URL: $($env:templateUrl)"
          Add-Content -Encoding UTF8 -Path $env:GITHUB_OUTPUT -Value "currentTemplateUrl=$($env:templateUrl)"
          Write-Host "COSMO Alpaca Template URL: $($env:ALPACA_TEMPLATE_URL)"
          Add-Content -Encoding UTF8 -Path $env:GITHUB_OUTPUT -Value "alpacaTemplateUrl=$($env:ALPACA_TEMPLATE_URL)"

  UpdateSystemFiles:
    name: Update AL-Go and COSMO Alpaca System Files
    needs: [ Initialization ]
    if: (!failure()) && (!cancelled()) && (needs.Initialization.outputs.currentTemplateUrl != needs.Initialization.outputs.alpacaTemplateUrl)
    uses: ./.github/workflows/_AlpacaUpdateSystemFiles.yaml
    secrets: inherit
    with:
      updateALGoSystemFiles: true
      updateAlpacaSystemFiles: true
      templateUrl: ${{ needs.Initialization.outputs.alpacaTemplateUrl }}
      branch: ${{ github.ref_name }}
      directCommit: true
      downloadLatest: true
      useInputCommitOptions: true

  
  